feature_extractor:
  SiftExtraction_num_octaves: 4
  SiftExtraction_octave_resolution: 3
  SiftExtraction_peak_threshold: 0.0066666666666666671
  SiftExtraction_edge_threshold: 10.0
  SiftExtraction_dsp_min_scale: 0.1666666666666666
  SiftExtraction_dsp_max_scale: 3.0
  SiftExtraction_dsp_num_scales: 10

matcher:
  SiftMatching_max_ratio: 0.80000000000000004
  SiftMatching_max_distance: 0.69999999999999996
  TwoViewGeometry_min_num_inliers: 15
  TwoViewGeometry_max_error: 4.0
  TwoViewGeometry_confidence: 0.999
  TwoViewGeometry_min_inlier_ratio: 0.25
  SequentialMatching_overlap: 10
  SequentialMatching_quadratic_overlap: 1 
  ExhaustiveMatching_block_size: 50

mapper:
  Mapper_min_num_matches: 15
  Mapper_ignore_watermarks: 0
  Mapper_multiple_models: 1
  Mapper_max_num_models: 50
  Mapper_max_model_overlap: 20
  Mapper_min_model_size: 10
  Mapper_init_image_id1: -1
  Mapper_init_image_id2: -1
  Mapper_init_num_trials: 200
  Mapper_extract_colors: 1
  Mapper_num_threads: -1
  Mapper_min_focal_length_ratio: 0.10000000000000001
  Mapper_max_focal_length_ratio: 10
  Mapper_max_extra_param: 1
  Mapper_ba_refine_focal_length: 1
  Mapper_ba_refine_principal_point: 0
  Mapper_ba_refine_extra_params: 1
  Mapper_ba_local_num_images: 6
  Mapper_ba_local_function_tolerance: 0
  Mapper_ba_local_max_num_iterations: 25
  Mapper_ba_global_images_ratio: 1.1000000000000001
  Mapper_ba_global_points_ratio: 1.1000000000000001
  Mapper_ba_global_images_freq: 500
  Mapper_ba_global_points_freq: 250000
  Mapper_ba_global_function_tolerance: 0
  Mapper_ba_global_max_num_iterations: 50
  Mapper_ba_global_max_refinements: 5
  Mapper_ba_global_max_refinement_change: 0.00050000000000000001
  Mapper_ba_local_max_refinements: 2
  Mapper_ba_local_max_refinement_change: 0.001
  Mapper_ba_use_gpu: 0
  Mapper_ba_gpu_index: -1
  Mapper_ba_min_num_residuals_for_cpu_multi_threading: 50000
  Mapper_snapshot_images_freq: 0
  Mapper_fix_existing_images: 0
  Mapper_init_min_num_inliers: 100
  Mapper_init_max_error: 4
  Mapper_init_max_forward_motion: 0.94999999999999996
  Mapper_init_min_tri_angle: 16
  Mapper_init_max_reg_trials: 2
  Mapper_abs_pose_max_error: 12
  Mapper_abs_pose_min_num_inliers: 30
  Mapper_abs_pose_min_inlier_ratio: 0.25
  Mapper_filter_max_reproj_error: 4
  Mapper_filter_min_tri_angle: 1.5
  Mapper_max_reg_trials: 3
  Mapper_local_ba_min_tri_angle: 6
  Mapper_tri_max_transitivity: 1
  Mapper_tri_create_max_angle_error: 2
  Mapper_tri_continue_max_angle_error: 2
  Mapper_tri_merge_max_reproj_error: 4
  Mapper_tri_complete_max_reproj_error: 4
  Mapper_tri_complete_max_transitivity: 5
  Mapper_tri_re_max_angle_error: 5
  Mapper_tri_re_min_ratio: 0.20000000000000001
  Mapper_tri_re_max_trials: 1
  Mapper_tri_min_angle: 1.5
  Mapper_tri_ignore_two_view_tracks: 1
